### ISSUE TITLE
Null Pointer Error when running MultipleRenderTargetTest from LwjglTestStarter

### ISSUE THREAD

**Issue by jlnguy** [Multi-Branch-Drifting-2410/libgdx#9]
#### Issue details

Null Pointer Error when running MultipleRenderTargetTest from LwjglTestStarter
#### Reproduction steps/code

Run LwjglTestStarter.java
Select MultipleRenderTargetTest
Enjoy the error message
#### Error message / Stack Trace?

```
> Exception in thread "LWJGL Application" java.lang.NullPointerException
>   at com.badlogic.gdx.tests.g3d.MultipleRenderTargetTest$MRTFrameBuffer.build(MultipleRenderTargetTest.java:561)
>   at com.badlogic.gdx.tests.g3d.MultipleRenderTargetTest$MRTFrameBuffer.<init>(MultipleRenderTargetTest.java:483)
>   at com.badlogic.gdx.tests.g3d.MultipleRenderTargetTest.create(MultipleRenderTargetTest.java:146)
>   at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
>   at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

**Comment by jlnguy** [comment]
Tomski says: You need to enable GL30 to run this test.

Which actually we need to enable GL20 because that's what's being called but so far I haven't gotten it to work yet.
